/*
  # Enable RLS on Missing Tables

  1. Security Fix
    - Enable RLS on all tables that currently have it disabled
    - Add basic restrictive policies
    
  2. Tables to Fix
    - All tables with RLS disabled from security audit
    
  3. Security
    - Enables RLS to enforce row-level security
    - Adds authenticated user policies where appropriate
*/

-- Enable RLS on tables that are missing it
ALTER TABLE IF EXISTS admin_data_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS admin_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ai_agent_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ai_generations ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS browser_captures ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS chatbot_integrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS coin_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS company_crawl_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS company_embeddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS company_knowledge_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS company_multi_site_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS custom_instructions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS energy_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS extracted_entities ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS mission_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS onboarding_sequences ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS pitch_decks ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS prospects ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public_chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public_chat_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS scan_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS scan_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS scan_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS social_graph_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS uploaded_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_coins ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_energy ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_subscriptions ENABLE ROW LEVEL SECURITY;